"""Initial migration

Revision ID: afd4c7319df4
Revises: 93db9008534b
Create Date: 2025-02-20 10:38:49.531642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd4c7319df4'
down_revision: Union[str, None] = '93db9008534b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        'games',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('mode', sa.Enum('REMOTE', 'AI', name='gamemode'), nullable=True),
        sa.Column('current_player', sa.Enum('X', 'O', 'T', name='playersymbol'), nullable=True),
        sa.Column('active_board', sa.Integer(), nullable=True),
        sa.Column('watchers_count', sa.Integer(), nullable=True),
        sa.Column('winner', sa.Enum('X', 'O', 'T', name='playersymbol'), nullable=True),
        sa.Column('last_move_timestamp', sa.DateTime(), nullable=True),
        sa.Column('move_count', sa.Integer(), nullable=True),
        sa.Column('global_board', sa.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'players',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('game_id', sa.String(), nullable=True),
        sa.Column('symbol', sa.Enum('X', 'O', 'T', name='playersymbol'), nullable=True),
        sa.Column('status', sa.Enum('PLAYER', 'WATCHER', name='playerstatus'), nullable=True),
        sa.Column('join_order', sa.Integer(), nullable=True),
        sa.Column('last_active', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
